### Environment and variables ##################################################

.upgo_env <- rlang::env()

user_agents <- c(
  paste0("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ",
         "(KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"),
  paste0("Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, ",
         "like Gecko) Chrome/72.0.3626.121 Safari/537.36"),
  paste0("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ",
         "(KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"),
  paste0("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ",
         "(KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"),
  paste0("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like ",
         "Gecko) Chrome/44.0.2403.157 Safari/537.36"),
  paste0("Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, ",
         "like Gecko) Chrome/60.0.3112.90 Safari/537.36"),
  paste0("Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like ",
         "Gecko) Chrome/72.0.3626.121 Safari/537.36"))

possible_cities <-
  c("abilene", "akroncanton", "albanyga", "albany", "albuquerque", "altoona",
    "amarillo", "ames", "anchorage", "annapolis", "annarbor", "appleton",
    "asheville", "ashtabula", "athensga", "athensohio", "atlanta", "auburn",
    "augusta", "austin", "bakersfield", "baltimore", "batonrouge",
    "battlecreek", "beaumont", "bellingham", "bemidji", "bend", "billings",
    "binghamton", "bham", "bismarck", "bloomington", "bn", "boise", "boone",
    "boston", "boulder", "bgky", "bozeman", "brainerd", "brownsville",
    "brunswick", "buffalo", "butte", "capecod", "catskills", "cedarrapids",
    "cenla", "centralmich", "cnj", "chambana", "charleston", "charlestonwv",
    "charlotte", "charlottesville", "chattanooga", "chautauqua", "chicago",
    "chico", "chillicothe", "cincinnati", "clarksville", "cleveland",
    "clovis", "collegestation", "cosprings", "columbiamo", "columbia",
    "columbusga", "columbus", "cookeville", "corpuschristi", "corvallis",
    "chambersburg", "dallas", "danville", "daytona", "dayton", "decatur",
    "nacogdoches", "delaware", "delrio", "denver", "desmoines", "detroit",
    "dothan", "dubuque", "duluth", "eastco", "newlondon", "eastky", "montana",
    "eastnc", "martinsburg", "easternshore", "eastidaho", "eastoregon",
    "eauclaire", "elko", "elmira", "elpaso", "erie", "eugene", "evansville",
    "fairbanks", "fargo", "farmington", "fayar", "fayetteville",
    "fingerlakes", "flagstaff", "flint", "shoals", "florencesc", "keys",
    "fortcollins", "fortdodge", "fortsmith", "fortwayne", "frederick",
    "fredericksburg", "fresno", "fortmyers", "gadsden", "gainesville",
    "galveston", "glensfalls", "goldcountry", "grandforks", "grandisland",
    "grandrapids", "greatfalls", "greenbay", "greensboro", "greenville",
    "gulfport", "hanford", "harrisburg", "harrisonburg", "hartford",
    "hattiesburg", "honolulu", "cfl", "helena", "hickory", "rockies",
    "hiltonhead", "holland", "houma", "houston", "hudsonvalley", "humboldt",
    "huntington", "huntsville", "imperial", "indianapolis", "inlandempire",
    "iowacity", "ithaca", "jxn", "jackson", "jacksontn", "jacksonville",
    "onslow", "janesville", "jerseyshore", "jonesboro", "joplin", "kalamazoo",
    "kalispell", "kansascity", "kenai", "kpr", "racine", "killeen",
    "kirksville", "klamath", "knoxville", "kokomo", "lacrosse", "lafayette",
    "tippecanoe", "lakecharles", "lakeland", "loz", "lancaster", "lansing",
    "laredo", "lasalle", "lascruces", "lasvegas", "lawrence", "lawton",
    "allentown", "lewiston", "lexington", "limaohio", "lincoln", "littlerock",
    "logan", "longisland", "losangeles", "louisville", "lubbock", "lynchburg",
    "macon", "madison", "maine", "ksu", "mankato", "mansfield", "masoncity",
    "mattoon", "mcallen", "meadville", "medford", "memphis", "mendocino",
    "merced", "meridian", "milwaukee", "minneapolis", "missoula", "mobile",
    "modesto", "mohave", "monroe", "monroemi", "monterey", "montgomery",
    "morgantown", "moseslake", "muncie", "muskegon", "myrtlebeach",
    "nashville", "nh", "newhaven", "neworleans", "blacksburg", "newyork",
    "norfolk", "lakecity", "nd", "nesd", "nmi", "wheeling", "northernwi",
    "newjersey", "northmiss", "northplatte", "nwct", "nwga", "nwks", "enid",
    "ocala", "odessa", "ogden", "okaloosa", "oklahomacity", "olympic",
    "omaha", "oneonta", "orangecounty", "oregoncoast", "orlando",
    "outerbanks", "owensboro", "palmsprings", "panamacity", "parkersburg",
    "pensacola", "peoria", "philadelphia", "phoenix", "csd", "pittsburgh",
    "plattsburgh", "poconos", "porthuron", "portland", "potsdam", "prescott",
    "provo", "pueblo", "pullman", "quadcities", "raleigh", "rapidcity",
    "reading", "redding", "reno", "providence", "richmondin", "richmond",
    "roanoke", "rmn", "rochester", "rockford", "roseburg", "roswell",
    "sacramento", "saginaw", "salem", "salina", "saltlakecity", "sanangelo",
    "sanantonio", "sandiego", "sandusky", "slo", "sanmarcos", "santabarbara",
    "santafe", "santamaria", "sarasota", "savannah", "scottsbluff",
    "scranton", "seattle", "sfbay", "sheboygan", "showlow", "shreveport",
    "sierravista", "siouxcity", "siouxfalls", "siskiyou", "skagit",
    "southbend", "southcoast", "sd", "juneau", "ottumwa", "seks", "semo",
    "carbondale", "smd", "swv", "miami", "southjersey", "swks", "swmi",
    "marshall", "natchez", "bigbend", "swva", "spacecoast", "spokane",
    "springfieldil", "springfield", "pennstate", "statesboro", "staugustine",
    "stcloud", "stgeorge", "stillwater", "stjoseph", "stlouis", "stockton",
    "susanville", "syracuse", "tallahassee", "tampa", "terrehaute",
    "texarkana", "texoma", "thumb", "toledo", "topeka", "treasure",
    "tricities", "tucson", "tulsa", "tuscaloosa", "tuscarawas", "twinfalls",
    "twintiers", "easttexas", "up", "utica", "valdosta", "ventura", "vermont",
    "victoriatx", "visalia", "waco", "washingtondc", "waterloo", "watertown",
    "wausau", "wenatchee", "quincy", "westky", "westmd", "westernmass",
    "westslope", "wv", "wichitafalls", "wichita", "williamsport",
    "wilmington", "winchester", "winstonsalem", "worcester", "wyoming",
    "yakima", "york", "youngstown", "yubasutter", "yuma", "zanesville",
    "toronto", "montreal", "vancouver"
  )

country_list <-
  c("Afghanistan", "\u00c5land Islands", "Albania", "Algeria",
    "American Samoa", "Andorra", "Angola", "Anguilla", "Antigua & Barbuda",
    "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan",
    "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium",
    "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia",
    "Bonaire, Sint Eustatius and Saba", "Bosnia and Herzegovina", "Botswana",
    "Brazil", "British Virgin Islands", "Brunei", "Bulgaria", "Burkina Faso",
    "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde",
    "Cayman Islands", "Central African Republic", "Chad", "Chile", "China",
    "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros",
    "Congo", "Cook Islands", "Costa Rica", "Croatia", "Cuba", "Cura\u00e7ao",
    "Cyprus", "Czech Republic", "Democratic Republic of the Congo", "Denmark",
    "Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador",
    "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia",
    "Ethiopia", "Falkland Islands (Malvinas)", "Faroe Islands", "Fiji",
    "Finland", "France", "French Guiana", "French Polynesia", "Gabon",
    "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece",
    "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey",
    "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hong Kong",
    "Hungary", "Iceland", "India", "Indonesia", "Iraq", "Ireland",
    "Isle of Man", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan",
    "Jersey", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait",
    "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
    "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia",
    "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta",
    "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte",
    "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro",
    "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru",
    "Nepal", "Netherlands", "New Caledonia", "New Zealand", "Nicaragua",
    "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands",
    "Norway", "Oman", "Pakistan", "Palau", "Palestinian Territories",
    "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
    "Pitcairn Islands", "Poland", "Portugal", "Puerto Rico", "Qatar",
    "R\u00e9union", "Romania", "Russia", "Rwanda", "Saint Barth\u00e9lemy",
    "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia", "Saint Martin",
    "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "Samoa",
    "San Marino", "S\u00e3o Tom\u00e9 and Pr\u00edncipe", "Saudi Arabia",
    "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore",
    "Sint Maarten", "Slovakia", "Slovenia", "Solomon Islands", "Somalia",
    "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka",
    "Sudan", "Suriname", "Svalbard and Jan Mayen", "Swaziland", "Sweden",
    "Switzerland", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Togo",
    "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan",
    "Turks and Caicos Islands", "Tuvalu", "U.S. Virgin Islands", "Uganda",
    "Ukraine", "United Arab Emirates", "United Kingdom", "United States",
    "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam",
    "Wallis and Futuna", "Yemen", "Zambia", "Zimbabwe"
  )

country_match <-
  dplyr::tibble(
    country = country_list,
    code =
      c("AF", "AX", "AL", "DZ", "AS", "AD", "AN", "AI", "AG", "AR", "AM", "AW",
        "AU", "AT", "AZ", "BS", "BH", "BD", "BB", "BY", "BE", "BZ", "BJ", "BM",
        "BT", "BO", "BQ", "BA", "BW", "BR", "VG", "BN", "BG", "BF", "BI", "KH",
        "CM", "CA", "CV", "KY", "CF", "TD", "CL", "CN", "CX", "CC", "CO", "KM",
        "CG", "CK", "CR", "HR", "CU", "CW", "CY", "CZ", "CD", "DK", "DJ", "DM",
        "DO", "TL", "EC", "EG", "SV", "GQ", "ER", "EE", "ET", "FK", "FO", "FJ",
        "FI", "FR", "GF", "PF", "GA", "GM", "GE", "DE", "GH", "GI", "GR", "GL",
        "GD", "GP", "GU", "GT", "GG", "GN", "GW", "GY", "HT", "HN", "HK", "HU",
        "IS", "IN", "ID", "IR", "IE", "IM", "IL", "IT", "CI", "JM", "JP", "JE",
        "JO", "KZ", "KE", "KI", "XK", "KW", "KG", "LA", "LV", "LB", "LS", "LR",
        "LY", "LI", "LT", "LU", "MO", "MK", "MG", "MW", "MY", "MV", "ML", "MT",
        "MH", "MQ", "MR", "MU", "YT", "MX", "FM", "MD", "MC", "MN", "ME", "MS",
        "MA", "MZ", "MM", "NA", "NR", "NP", "NL", "NC", "NZ", "NI", "NE", "NG",
        "NU", "NF", "MP", "NO", "OM", "PK", "PW", "PS", "PA", "PG", "PY", "PE",
        "PH", "PN", "PL", "PT", "PR", "QA", "RE", "RO", "RU", "RW", "BL", "SH",
        "KN", "LC", "MF", "PM", "VC", "WS", "SM", "ST", "SA", "SN", "RS", "SC",
        "SL", "SG", "SX", "SK", "SI", "SB", "SO", "ZA", "KR", "SS", "ES", "LK",
        "SD", "SR", "SJ", "SZ", "SE", "CH", "TW", "TJ", "TZ", "TH", "TG", "TO",
        "TT", "TN", "TR", "TM", "TC", "TV", "VI", "UG", "UA", "AE", "GB", "US",
        "UY", "UZ", "VU", "VE", "VN", "WF", "YE", "ZM", "ZW")
    )

US_states <-
  c("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID",
    "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS",
    "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK",
    "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV",
    "WI", "WY")


### Quiet R CMD check ##########################################################

if(getRversion() >= "2.15.1") {
  utils::globalVariables(c(".", "remDr", ".con", "i", "j", ".upgo_env"))
}
